# Generated by Django 6.0.5 on 2026-06-29 11:14

import account.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="شناسه گروه تلگرام"
                    ),
                ),
                ("theme", models.IntegerField(default=1, verbose_name="تم")),
                (
                    "max_warnings",
                    models.IntegerField(default=3, verbose_name="حداکثر اخطار"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="نام گروه"
                    ),
                ),
                (
                    "off",
                    models.BooleanField(default=False, verbose_name="خاموش بودن ربات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "group_lock",
                    models.BooleanField(default=False, verbose_name="قفل کلی گروه"),
                ),
                (
                    "dice_option",
                    models.BooleanField(default=True, verbose_name="تاس متوالی"),
                ),
                (
                    "warning_enabled",
                    models.BooleanField(default=True, verbose_name="اخطار خودکار"),
                ),
                (
                    "is_speaker_enabled",
                    models.BooleanField(default=False, verbose_name="اسپیکر فعال"),
                ),
                (
                    "locks",
                    models.JSONField(
                        default=account.models.default_locks,
                        verbose_name="قفل\u200cهای گروه",
                    ),
                ),
                (
                    "enabled_commands",
                    models.JSONField(
                        default=account.models.default_commands,
                        verbose_name="دستورات فعال گروه",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال بودن گروه"),
                ),
                (
                    "subscription_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ انقضا"
                    ),
                ),
                (
                    "ad_enabled",
                    models.BooleanField(default=True, verbose_name="دریافت تبلیغات"),
                ),
                ("ad_disabled_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "گروه",
                "verbose_name_plural": "گروه\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("duration_days", models.IntegerField()),
                ("created_by", models.BigIntegerField(verbose_name="سازنده")),
                ("used_by_owner", models.BigIntegerField(blank=True, null=True)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used_by_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.telegramgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_user_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "telegram_chat_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["telegram_chat_id"],
                        name="account_tel_telegra_e9c482_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LearnedResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trigger", models.CharField(max_length=255)),
                ("response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.BigIntegerField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learned_responses",
                        to="account.telegramgroup",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["group", "trigger"],
                        name="account_lea_group_i_d88b7c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TelegramGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_chat_id", models.BigIntegerField(verbose_name="شناسه گروه")),
                (
                    "telegram_user_id",
                    models.BigIntegerField(verbose_name="شناسه کاربر"),
                ),
                ("card_number", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "card_number2",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "card_number3",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("card_name", models.CharField(blank=True, max_length=100, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("alias", models.CharField(blank=True, max_length=255, null=True)),
                ("point", models.IntegerField(blank=True, default=0, null=True)),
                ("message_count", models.IntegerField(default=0)),
                ("warnings", models.IntegerField(default=0)),
                ("xp_total", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("role", models.CharField(default="member", max_length=20)),
                ("is_owner", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_vip", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.telegramgroup",
                        verbose_name="گروه",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضو گروه",
                "verbose_name_plural": "اعضای گروه",
                "ordering": ["-xp_total", "-level"],
                "indexes": [
                    models.Index(
                        fields=["telegram_chat_id", "telegram_user_id"],
                        name="account_tel_telegra_76243d_idx",
                    )
                ],
            },
        ),
    ]
