# Generated by Django 6.0.2 on 2026-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="fee_percent",
            field=models.IntegerField(default=0, verbose_name="درصد کارمزد"),
        ),
        migrations.CreateModel(
            name="DiceRollStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_chat_id", models.BigIntegerField()),
                ("telegram_user_id", models.BigIntegerField()),
                ("value", models.SmallIntegerField()),
                ("rolled_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["telegram_chat_id", "telegram_user_id", "rolled_at"],
                        name="account_dic_telegra_6a495c_idx",
                    )
                ],
            },
        ),
    ]
