# Generated by Django 6.0.2 on 2026-07-01 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_welcome_default_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="antiraid_enabled",
            field=models.BooleanField(default=False, verbose_name="حالت ضد رید فعال"),
        ),
        migrations.AddField(
            model_name="telegramgroup",
            name="captcha_enabled",
            field=models.BooleanField(default=False, verbose_name="کپچا فعال"),
        ),
        migrations.AddField(
            model_name="telegramgroup",
            name="captcha_timeout",
            field=models.IntegerField(default=180, verbose_name="مهلت کپچا (ثانیه)"),
        ),
        migrations.AddField(
            model_name="telegramgroup",
            name="log_channel_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="شناسه کانال لاگ"
            ),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("created_by", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="account.telegramgroup",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["group", "name"], name="account_not_group_i_8b59cb_idx"
                    )
                ],
                "unique_together": {("group", "name")},
            },
        ),
    ]
