# Generated by Django 6.0.5 on 2026-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_captcha_antiraid_log_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="night_end_hour",
            field=models.IntegerField(default=8, verbose_name="ساعت پایان حالت شب"),
        ),
        migrations.AddField(
            model_name="telegramgroup",
            name="night_mode_enabled",
            field=models.BooleanField(default=False, verbose_name="حالت شب فعال"),
        ),
        migrations.AddField(
            model_name="telegramgroup",
            name="night_start_hour",
            field=models.IntegerField(default=0, verbose_name="ساعت شروع حالت شب"),
        ),
        migrations.AddField(
            model_name="telegramgroup",
            name="rules_text",
            field=models.TextField(blank=True, null=True, verbose_name="قوانین گروه"),
        ),
    ]
