# Generated by Django 6.0.5 on 2026-07-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_telegramgroup_night_end_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="telegram_emoji_enabled",
            field=models.BooleanField(
                default=False,
                verbose_name="استیکر/ایموجی متحرک تلگرام برای بازی\u200cها",
            ),
        ),
    ]
