# Generated by Django 6.0.5 on 2026-07-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_telegramgroup_fee_percent_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_chat_id", models.BigIntegerField(db_index=True)),
                ("telegram_user_id", models.BigIntegerField(db_index=True)),
                ("admin_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("admin_increase", "افزایش ادمین"),
                            ("admin_decrease", "کاهش ادمین"),
                            ("admin_clear", "تسویه"),
                            ("bet", "شرط"),
                            ("win", "برد"),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("balance_after", models.BigIntegerField()),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["telegram_chat_id", "telegram_user_id", "-created_at"],
                        name="account_wal_telegra_833cce_idx",
                    ),
                    models.Index(fields=["type"], name="account_wal_type_9daf39_idx"),
                ],
            },
        ),
    ]
