# Generated by Django 6.0.5 on 2026-07-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_telegramgroup_increase_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("admin_increase", "افزایش ادمین"),
                    ("admin_decrease", "کاهش ادمین"),
                    ("admin_clear", "تسویه"),
                    ("bet", "شرط"),
                    ("win", "برد"),
                    ("fee", "حق واسطه"),
                ],
                max_length=32,
            ),
        ),
    ]
