# Generated by Django 6.0.5 on 2026-07-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0032_withdrawalrequest_settle_kind"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminactivitysession",
            new_name="account_adm_telegra_c2f23f_idx",
            old_name="acct_act_sess_chat_start",
        ),
        migrations.RenameIndex(
            model_name="adminactivitysession",
            new_name="account_adm_telegra_59fd00_idx",
            old_name="acct_act_sess_chat_admin",
        ),
        migrations.RenameIndex(
            model_name="challengeentry",
            new_name="account_cha_challen_2b0efe_idx",
            old_name="account_cha_challen_e1_idx",
        ),
        migrations.RenameIndex(
            model_name="challengeentry",
            new_name="account_cha_challen_40bf95_idx",
            old_name="account_cha_challen_e2_idx",
        ),
        migrations.RenameIndex(
            model_name="dicegamehistory",
            new_name="account_dic_telegra_515d3a_idx",
            old_name="account_dice_chat_created_idx",
        ),
        migrations.RenameIndex(
            model_name="dicegamehistory",
            new_name="account_dic_telegra_cc1c7c_idx",
            old_name="account_dice_chat_session_idx",
        ),
        migrations.RenameIndex(
            model_name="financerequestban",
            new_name="account_fin_telegra_1b4015_idx",
            old_name="account_fin_telegra_7f2a1b_idx",
        ),
        migrations.RenameIndex(
            model_name="gameplaylog",
            new_name="account_gam_telegra_abadd8_idx",
            old_name="account_gam_telegra_pl1_idx",
        ),
        migrations.RenameIndex(
            model_name="groupchallenge",
            new_name="account_gro_telegra_3d617b_idx",
            old_name="account_gro_telegra_ch1_idx",
        ),
        migrations.RenameIndex(
            model_name="groupchallenge",
            new_name="account_gro_telegra_80414f_idx",
            old_name="account_gro_telegra_ch2_idx",
        ),
        migrations.AlterField(
            model_name="groupchallenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("dice", "چالش تاس"),
                    ("dart", "چالش دارت"),
                    ("luck", "چالش شانس"),
                    ("football", "چالش فوتبال"),
                    ("basketball", "چالش بسکتبال"),
                    ("max_bet", "بیشترین مبلغ شرط"),
                    ("max_count", "بیشترین تعداد"),
                    ("max_increase", "بیشترین افزایش موجودی"),
                    ("sum_increase", "مجموع افزایش موجودی"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="groupchallenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "فعال"),
                    ("ended", "پایان\u200cیافته"),
                    ("cancelled", "لغو شده"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
    ]
