from django.db import migrations, models

from account import migration_utils as idem


TG = "account_telegramgroup"
LS = "account_leaguestanding"


def forwards(apps, schema_editor):
    idem.add_column_sql(
        schema_editor, TG, "league_enabled", "boolean DEFAULT false NOT NULL"
    )
    if not idem.table_exists(schema_editor, LS):
        with schema_editor.connection.cursor() as cursor:
            if schema_editor.connection.vendor == "postgresql":
                cursor.execute(
                    f'''
                    CREATE TABLE "{LS}" (
                        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        "telegram_chat_id" bigint NOT NULL,
                        "telegram_user_id" bigint NOT NULL,
                        "wager_total" bigint NOT NULL DEFAULT 0,
                        "claimed_level" smallint NOT NULL DEFAULT 0 CHECK ("claimed_level" >= 0),
                        "updated_at" timestamp with time zone NOT NULL
                    );
                    '''
                )
            else:
                cursor.execute(
                    f'''
                    CREATE TABLE "{LS}" (
                        "id" integer PRIMARY KEY AUTOINCREMENT,
                        "telegram_chat_id" bigint NOT NULL,
                        "telegram_user_id" bigint NOT NULL,
                        "wager_total" bigint NOT NULL DEFAULT 0,
                        "claimed_level" smallint NOT NULL DEFAULT 0,
                        "updated_at" datetime NOT NULL
                    );
                    '''
                )
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "account_leaguestanding_telegram_chat_id_idx" '
                f'ON "{LS}" ("telegram_chat_id");'
            )
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "account_leaguestanding_telegram_user_id_idx" '
                f'ON "{LS}" ("telegram_user_id");'
            )
    idem.ensure_index(
        schema_editor,
        f'CREATE INDEX "account_lea_telegra_wager_idx" ON "{LS}" '
        f'("telegram_chat_id", "wager_total" DESC);',
        "account_lea_telegra_wager_idx",
    )
    if (
        schema_editor.connection.vendor == "postgresql"
        and not idem.constraint_exists(schema_editor, "uniq_tg_league_standing")
    ):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                f'ALTER TABLE "{LS}" ADD CONSTRAINT "uniq_tg_league_standing" '
                f'UNIQUE ("telegram_chat_id", "telegram_user_id");'
            )


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0035_telegramgroup_transfer_enabled"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(forwards, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="telegramgroup",
                    name="league_enabled",
                    field=models.BooleanField(
                        default=False,
                        help_text="اگر روشن باشد، حجم شرط کاربران در لیگ ثبت و جوایز پله‌ای پرداخت می‌شود.",
                        verbose_name="لیگ شرط",
                    ),
                ),
                migrations.CreateModel(
                    name="LeagueStanding",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("telegram_chat_id", models.BigIntegerField(db_index=True)),
                        ("telegram_user_id", models.BigIntegerField(db_index=True)),
                        ("wager_total", models.BigIntegerField(default=0, verbose_name="مجموع شرط")),
                        (
                            "claimed_level",
                            models.PositiveSmallIntegerField(
                                default=0,
                                help_text="۰ = هنوز جایزه‌ای نگرفته؛ ۱..۵ = آخرین پله پرداخت‌شده",
                                verbose_name="آخرین پلهٔ جایزه‌گرفته",
                            ),
                        ),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "رتبه لیگ",
                        "verbose_name_plural": "رتبه‌های لیگ",
                    },
                ),
                migrations.AddIndex(
                    model_name="leaguestanding",
                    index=models.Index(
                        fields=["telegram_chat_id", "-wager_total"],
                        name="account_lea_telegra_wager_idx",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="leaguestanding",
                    constraint=models.UniqueConstraint(
                        fields=("telegram_chat_id", "telegram_user_id"),
                        name="uniq_tg_league_standing",
                    ),
                ),
            ],
        ),
    ]
