# Generated by Django 6.0.5 on 2026-08-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0042_telegramgroup_league_board_theme"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="leaguestanding",
            new_name="account_lea_telegra_40418d_idx",
            old_name="account_lea_telegra_wager_idx",
        ),
        migrations.RenameIndex(
            model_name="leaguestanding",
            new_name="account_lea_telegra_2bebb7_idx",
            old_name="account_lea_tg_season_idx",
        ),
    ]
