# Generated by Django 6.0.5 on 2026-08-16 05:44

from django.db import migrations

from account import migration_utils as idem


def forwards(apps, schema_editor):
    idem.rename_index_if_needed(
        schema_editor,
        "account_lea_telegra_wager_idx",
        "account_lea_telegra_40418d_idx",
    )
    idem.rename_index_if_needed(
        schema_editor,
        "account_lea_tg_season_idx",
        "account_lea_telegra_2bebb7_idx",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0042_telegramgroup_league_board_theme"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(forwards, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="leaguestanding",
                    new_name="account_lea_telegra_40418d_idx",
                    old_name="account_lea_telegra_wager_idx",
                ),
                migrations.RenameIndex(
                    model_name="leaguestanding",
                    new_name="account_lea_telegra_2bebb7_idx",
                    old_name="account_lea_tg_season_idx",
                ),
            ],
        ),
    ]
