"""
Django settings for rubika_db project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-eea9&dhlv8e8_rdf-av$kps$js^^k=qtot4^#1$e5au&4p_^0k")

DEBUG = os.getenv("DEBUG", "true").lower() in ("1", "true", "yes")

_allowed = os.getenv("ALLOWED_HOSTS", "tasino.spayerx.ir,localhost,127.0.0.1")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]
if "*" not in ALLOWED_HOSTS and "tasino.spayerx.ir" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("tasino.spayerx.ir")

# از WEBHOOK_HOST هم دامین را بگیر (مثلاً tasino2.spayerx.ir)
_webhook_host = (os.getenv("WEBHOOK_HOST") or "").strip().rstrip("/")
if _webhook_host:
    from urllib.parse import urlparse
    _wh = urlparse(_webhook_host if "://" in _webhook_host else f"https://{_webhook_host}")
    if _wh.hostname and _wh.hostname not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_wh.hostname)

# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "django_jalali",
    "account",
    "wordfilter",
    "bot_setting",
    "scheduledmessage",
]

REDIS_URL = os.getenv(
    "BOT_REDIS_URL",
    "redis://127.0.0.1:6379/2"
)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "TIMEOUT": 172800,
    }
}


CSRF_COOKIE_PATH = '/'
CSRF_TRUSTED_ORIGINS = [
    "https://tasino.spayerx.ir",
    "http://tasino.spayerx.ir",
    "http://46.34.163.31:8001",
    "http://46.34.163.31:8002",
    "http://46.34.163.31:8003",
    "http://46.34.163.31:8004",
    "http://46.34.163.31:8005",
    "http://46.34.163.31:8006",
    "http://46.34.163.31:8101",
    "http://79.133.42.190:8001",
    "https://tasino.liara.run",
    "https://tasino2.liara.run",
    "https://tasino.runflare.run",
    "https://tasin2.runflare.run",
    "https://tasino3.runflare.run",
    "https://tasino4.runflare.run",
    "https://tasino5.runflare.run",
    "https://tasino6.runflare.run",
    "https://tasino7.runflare.run",
    "https://tasino8.runflare.run",
    "https://tasino9.runflare.run",
    "https://tasino10.runflare.run",
    "https://vira-webhoo23k.runflare.run",
]
# اضافه‌ها از env: CSRF_TRUSTED_ORIGINS=https://example.com
_csrf_extra = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if _csrf_extra:
    CSRF_TRUSTED_ORIGINS += [o.strip() for o in _csrf_extra.split(",") if o.strip()]

# خودکار از ALLOWED_HOSTS و WEBHOOK_HOST
for _host in ALLOWED_HOSTS:
    if _host in ("localhost", "127.0.0.1") or "*" in _host:
        continue
    for _scheme in ("https", "http"):
        _origin = f"{_scheme}://{_host}"
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)
if _webhook_host and _webhook_host not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(_webhook_host)

# پشت nginx / reverse-proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ROOT_URLCONF = "TasinoAiogram3.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ← این خط رو اضافه کن
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "TasinoAiogram3.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "rubika_disck/db.sqlite3",
#     }
# }

# LOCAL_DATABASE_URL = 'postgresql://root:kKi4SyE8qtXSQHn69EvbNjz5@olympus.liara.cloud:33895/postgres'



import dj_database_url
import os
#
# LOCAL_DATABASE_URL = 'postgresql://postgres:xeWHqnpKJX54m8XVpvnl@remote-pishgaman.runflare.com:31918/djangouposn_db'

LOCAL_DATABASE_URL = 'postgresql://postgres:1234@localhost:5432/tasino_db'

# LOCAL_DATABASE_URL = 'postgresql://postgres:ankTsE94IbVEbwh3WdHz@remote-pishgaman.runflare.com:30899/django-2pjf_db'

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', LOCAL_DATABASE_URL),
    ),
}


# اضافه کردن connect_timeout
for db in DATABASES.values():
    db.setdefault('OPTIONS', {})
    db['OPTIONS']['connect_timeout'] = 10



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'USER': 'root',
#         'PASSWORD': 'kKi4SyE8qtXSQHn69EvbNjz5',
#         'HOST': '185.143.232.244',  # این آی‌پیِ معادل همان olympus.liara.cloud است
#         'PORT': '33895',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fa-ir"


TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = True

# جلوگیری از ساخت مکرر migration برای تغییر نوع id (AutoField → BigAutoField)
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'static'
#
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = '/media/'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# آپلود دامپ بکاپ (تا ۵۱۲ مگ)
DATA_UPLOAD_MAX_MEMORY_SIZE = 512 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 64 * 1024 * 1024
# ─── Unfold Admin ────────────────────────────────────────────────────────────
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "تاسینو",
    "SITE_HEADER": "پنل مدیریت تاسینو",
    "SITE_SUBHEADER": "مدیریت ربات، گروه‌ها و مالی",
    "SITE_SYMBOL": "casino",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "ENVIRONMENT": "TasinoAiogram3.settings.unfold_environment",
    "DASHBOARD_CALLBACK": "TasinoAiogram3.admin_dashboard.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "خانه",
                "separator": True,
                "items": [
                    {"title": "داشبورد", "icon": "dashboard", "link": reverse_lazy("admin:index")},
                ],
            },
            {
                "title": "تنظیمات سراسری",
                "separator": True,
                "items": [
                    {"title": "لینکدونی و پشتیبانی", "icon": "link", "link": reverse_lazy("admin:bot_setting_botsiteconfig_change", args=[1])},
                    {"title": "بکاپ و بازیابی", "icon": "backup", "link": reverse_lazy("admin:bot_setting_databasebackuptool_changelist")},
                    {"title": "جوین اجباری", "icon": "lock", "link": reverse_lazy("admin:bot_setting_forcedjoinconfig_change", args=[1])},
                    {"title": "پیام‌های عضویت", "icon": "campaign", "link": reverse_lazy("admin:bot_setting_joinmessage_changelist")},
                ],
            },
            {
                "title": "گروه‌ها و اعضا",
                "separator": True,
                "items": [
                    {"title": "گروه‌ها", "icon": "groups", "link": reverse_lazy("admin:account_telegramgroup_changelist")},
                    {"title": "اعضا", "icon": "person", "link": reverse_lazy("admin:account_telegramgroupmember_changelist")},
                    {"title": "فیلتر کلمات", "icon": "filter_alt", "link": reverse_lazy("admin:wordfilter_wordfilter_changelist")},
                ],
            },
            {
                "title": "مالی و بازی",
                "separator": True,
                "items": [
                    {"title": "تراکنش‌ها", "icon": "payments", "link": reverse_lazy("admin:account_wallettransaction_changelist")},
                    {"title": "آمار تاس", "icon": "casino", "link": reverse_lazy("admin:account_dicerollstat_changelist")},
                    {"title": "لایسنس", "icon": "vpn_key", "link": reverse_lazy("admin:account_license_changelist")},
                ],
            },
            {
                "title": "پیام‌رسانی",
                "separator": True,
                "items": [
                    {"title": "پیام زمان‌بندی", "icon": "schedule", "link": reverse_lazy("admin:scheduledmessage_scheduledmessage_changelist")},
                    {"title": "یادگیری ربات", "icon": "school", "link": reverse_lazy("admin:account_learnedresponse_changelist")},
                    {"title": "یادداشت‌ها", "icon": "sticky_note_2", "link": reverse_lazy("admin:account_note_changelist")},
                ],
            },
        ],
    },
}


def unfold_environment(request):
    return ["تاسینو", "info"]
