"""
Django settings for rubika_db project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-eea9&dhlv8e8_rdf-av$kps$js^^k=qtot4^#1$e5au&4p_^0k")

DEBUG = os.getenv("DEBUG", "true").lower() in ("1", "true", "yes")

_allowed = os.getenv("ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "django_jalali",
    # my app
    # "core",
    "account",
    # "games",
    # "scheduler",
    "wordfilter",
    # "groupmessagelog",
    # 'messages_app.apps.MessagesAppConfig',
    # "GroupMute",
    # "wallet",
    # "Transaction",
    "bot_setting",
    "scheduledmessage",

]

REDIS_URL = os.getenv(
    "BOT_REDIS_URL",
    "redis://127.0.0.1:6379/2"
)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "TIMEOUT": 172800,
    }
}


CSRF_COOKIE_PATH = '/'
CSRF_TRUSTED_ORIGINS = [
    "http://46.34.163.31:8001",
    "http://46.34.163.31:8002",
    "http://46.34.163.31:8003",
    "http://46.34.163.31:8004",
    "http://46.34.163.31:8005",
    "http://46.34.163.31:8006",
    "http://46.34.163.31:8101",
    "https://tasino.liara.run",
    "https://tasino2.liara.run",
    "https://tasino.runflare.run",
    "https://tasin2.runflare.run",
    "https://tasino3.runflare.run",
    "https://tasino4.runflare.run",
    "https://tasino5.runflare.run",
    "https://tasino6.runflare.run",
    "https://tasino7.runflare.run",
    "https://tasino8.runflare.run",
    "https://tasino9.runflare.run",
    "https://tasino10.runflare.run",
    "https://vira-webhoo23k.runflare.run"
    # ... بقیه پورت‌ها
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ROOT_URLCONF = "TasinoAiogram3.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ← این خط رو اضافه کن
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "TasinoAiogram3.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "rubika_disck/db.sqlite3",
#     }
# }

# LOCAL_DATABASE_URL = 'postgresql://root:kKi4SyE8qtXSQHn69EvbNjz5@olympus.liara.cloud:33895/postgres'



import dj_database_url
import os
#
# LOCAL_DATABASE_URL = 'postgresql://postgres:xeWHqnpKJX54m8XVpvnl@remote-pishgaman.runflare.com:31918/djangouposn_db'

LOCAL_DATABASE_URL = 'postgresql://postgres:1234@localhost:5432/tasino_db'

# LOCAL_DATABASE_URL = 'postgresql://postgres:ankTsE94IbVEbwh3WdHz@remote-pishgaman.runflare.com:30899/django-2pjf_db'

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', LOCAL_DATABASE_URL),
    ),
}


# اضافه کردن connect_timeout
for db in DATABASES.values():
    db.setdefault('OPTIONS', {})
    db['OPTIONS']['connect_timeout'] = 10



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'USER': 'root',
#         'PASSWORD': 'kKi4SyE8qtXSQHn69EvbNjz5',
#         'HOST': '185.143.232.244',  # این آی‌پیِ معادل همان olympus.liara.cloud است
#         'PORT': '33895',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fa-ir"


TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'static'
#
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = '/media/'