# Generated by Django 6.0.5 on 2026-06-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JoinMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("text", models.TextField(verbose_name="متن پیام")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("priority", models.IntegerField(default=0, verbose_name="اولویت")),
                (
                    "is_forever",
                    models.BooleanField(default=False, verbose_name="بدون انقضا"),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع نمایش"
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان نمایش"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["priority", "-created_at"],
            },
        ),
    ]
