# Generated by Django 6.0.5 on 2026-07-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_setting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForcedJoinConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False, verbose_name="فعال")),
                (
                    "channel_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="شناسه کانال"
                    ),
                ),
                (
                    "channel_title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="نام کانال"
                    ),
                ),
                (
                    "channel_username",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="یوزرنیم"
                    ),
                ),
                (
                    "invite_link",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="لینک دعوت"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "جوین اجباری کانال",
                "verbose_name_plural": "جوین اجباری کانال",
            },
        ),
    ]
