# Generated by Django 6.0.5 on 2026-07-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_setting", "0002_forced_join_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_directory_url",
                    models.URLField(
                        default="https://t.me/TasinoBot",
                        help_text="آدرس دکمه «لینکدونی» در پیوی ربات",
                        max_length=512,
                        verbose_name="لینک لینکدونی",
                    ),
                ),
                (
                    "link_directory_title",
                    models.CharField(
                        default="🔥 بزرگترین لینکدونی",
                        max_length=64,
                        verbose_name="متن دکمه لینکدونی",
                    ),
                ),
                (
                    "support_url",
                    models.URLField(
                        default="https://t.me/Spayers",
                        max_length=512,
                        verbose_name="لینک پشتیبانی",
                    ),
                ),
                (
                    "support_title",
                    models.CharField(
                        default="گروه پشتیبانی",
                        max_length=64,
                        verbose_name="عنوان پشتیبانی",
                    ),
                ),
                (
                    "channel_url",
                    models.URLField(
                        blank=True,
                        default="https://t.me/TasinoBot",
                        max_length=512,
                        verbose_name="لینک کانال رسمی",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تنظیمات سراسری ربات",
                "verbose_name_plural": "تنظیمات سراسری ربات",
            },
        ),
    ]
