# Generated by Django 6.0.5 on 2026-07-15 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_alter_wallettransaction_type"),
        ("bot_setting", "0007_databasebackuptool"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupForcedJoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.BigIntegerField()),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("invite_link", models.URLField(max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forced_join",
                        to="account.telegramgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "جوین اجباری گروه",
                "verbose_name_plural": "جوین\u200cهای اجباری گروه\u200cها",
            },
        ),
    ]
