# Generated by Django 6.0.5 on 2026-07-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_setting", "0008_groupforcedjoin"),
    ]

    operations = [
        migrations.AddField(
            model_name="forcedjoinconfig",
            name="active_from",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="شروع زمان\u200cبندی"
            ),
        ),
        migrations.AddField(
            model_name="forcedjoinconfig",
            name="active_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="پایان زمان\u200cبندی"
            ),
        ),
    ]
