# Generated by Django 6.0.2 on 2026-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان پیام")),
                ("text", models.TextField(verbose_name="متن پیام")),
                (
                    "queue_ad_until_message",
                    models.BooleanField(
                        default=False, verbose_name="تعویق تبلیغات تا ارسال پیام"
                    ),
                ),
                (
                    "send_to_pv",
                    models.BooleanField(default=False, verbose_name="ارسال به پیوی"),
                ),
                (
                    "send_to_all",
                    models.BooleanField(
                        default=False, verbose_name="ارسال به همه گروه\u200cها"
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="شناسه گروه"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("interval", "دوره\u200cای (هر چند دقیقه یکبار)"),
                            ("fixed", "زمان مشخص (تاریخ و ساعت)"),
                        ],
                        default="interval",
                        max_length=10,
                        verbose_name="نوع زمان\u200cبندی",
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="فاصله زمانی (دقیقه)"
                    ),
                ),
                (
                    "ignore_group_ad_setting",
                    models.BooleanField(
                        default=False,
                        help_text="اگر فعال باشد حتی گروه\u200cهایی که تبلیغات را خاموش کرده\u200cاند نیز پیام را دریافت می\u200cکنند.",
                        verbose_name="نادیده گرفتن تنظیمات تبلیغات گروه",
                    ),
                ),
                (
                    "run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان دقیق ارسال"
                    ),
                ),
                (
                    "last_sent",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین ارسال"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "پیام زمان\u200cبندی\u200cشده",
                "verbose_name_plural": "پیام\u200cهای زمان\u200cبندی\u200cشده",
                "ordering": ["-is_active", "-id"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="scheduledme_is_acti_ee13aa_idx"
                    ),
                    models.Index(
                        fields=["run_at"], name="scheduledme_run_at_3e1b80_idx"
                    ),
                    models.Index(
                        fields=["chat_id"], name="scheduledme_chat_id_873d0a_idx"
                    ),
                ],
            },
        ),
    ]
