# Generated by Django 6.0.5 on 2026-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_panel", "0001_ad_loadout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adloadout",
            options={
                "ordering": ["-is_favorite", "name"],
                "verbose_name": "برنامه ساعت",
                "verbose_name_plural": "برنامه\u200cهای ساعت",
            },
        ),
        migrations.AlterField(
            model_name="adloadout",
            name="default_mode",
            field=models.CharField(
                choices=[
                    ("group", "تبلیغ گروه"),
                    ("pv", "تبلیغ ربات"),
                    ("bomb", "بمب"),
                    ("super", "سوپر بمب"),
                ],
                default="bomb",
                max_length=16,
                verbose_name="نوع پیش\u200cفرض (سازگاری)",
            ),
        ),
        migrations.AlterField(
            model_name="adloadout",
            name="ignore_group_ad_setting",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="adloadout",
            name="is_favorite",
            field=models.BooleanField(default=True, verbose_name="فعال برای پنل امروز"),
        ),
        migrations.AlterField(
            model_name="adloadout",
            name="name",
            field=models.CharField(max_length=120, verbose_name="نام برنامه"),
        ),
        migrations.AlterField(
            model_name="adloadout",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="adloadout",
            name="queue_ad_until_message",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="adloadout",
            name="slots",
            field=models.JSONField(default=list, verbose_name="ردیف\u200cها"),
        ),
    ]
