# Generated by Django 6.0.5 on 2026-06-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WordFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(verbose_name="شناسه گروه")),
                (
                    "word",
                    models.CharField(max_length=100, verbose_name="کلمه مسدود شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "کلمه فیلتر شده",
                "verbose_name_plural": "کلمات فیلتر شده",
                "ordering": ["chat_id", "word"],
                "indexes": [
                    models.Index(
                        fields=["chat_id"], name="wordfilter__chat_id_d5a798_idx"
                    )
                ],
                "unique_together": {("chat_id", "word")},
            },
        ),
    ]
